services:
  db:
    image: postgres:15
    container_name: scraper_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scraper_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    container_name: scraper_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /mnt/postgres_data/scraper_logs:/app/logs
      - /mnt/postgres_data/scraper_data:/scraper_data
    restart: unless-stopped
    networks:
      - scraper_network
    # healthcheck:
    #   test: ["CMD", "/usr/local/bin/healthcheck.sh"]
    #   interval: 2m
    #   timeout: 10s
    #   retries: 3
    #   start_period: 0s


# Volumes
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /mnt/postgres_data/pg_data
      o: bind

# Network
networks:
  scraper_network:
    driver: bridge
