version: "3.9"

services:
  db:
    image: postgres:15
    container_name: scraper_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    container_name: scraper_app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./logs:/app/logs
    restart: on-failure

volumes:
  pgdata:
    driver: local

# FOR PROD 
# volumes:
#   pgdata:
#     driver: local
#     driver_opts:
#       type: none
#       device: /mnt/disks/my_pg_disk
#       o: bind